project_one/app.py
from flask import Flask, render_template, redirect,Blueprint  #flask imports
from views import my_view

app = Flask(__name__) 

app.register_blueprint(my_view) #sets the blueprint

@app.errorhandler(404)   #error handling goes on the app page - it doesn't work nicely with blueprints! This route is for 404 errors
def page_not_found(e): #page_not_found is the function - (e) is the variable that has the error message. The e is build into flask
    return render_template("404.html", e=e) # picks the html page that shows for 404 errors


if __name__=="__main__":
    app.run(debug=True, port=8000) # debugging is activated and the project is set to hosted on port 8000 (debugging should only be used in testing).

project_one/views.py
from flask import render_template, redirect, url_for, Blueprint, request


my_view = Blueprint('my_view', __name__)

@my_view.route("/")    
def home():
    return render_template('index.html')

@my_view.route("/admin")   
def admin():
    return render_template('admin.html') 

@my_view.route("/page1")   
def pg1():
    return render_template('page1.html') 

@my_view.route("/page2")   
def pg2():
    return render_template('page2.html') 

@my_view.route("page3")   
def pg3():
    return render_template('page3.html') 

@my_view.route("/page4")   
def pg4():
    return render_template('page5.html') 

@my_view.route("/page5")   
def pg5():
    return render_template('page5.html') 

@my_view.route("/home")
@my_view.route("/js")
@my_view.route("/javascript")
def home_redirect():
    return redirect(url_for("my_view.home"))

project_one/templates/admin.html
{% extends 'base.html' %}
{% block content %}
<p> Future Content</p>
{% endblock %}

project_one/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{url_for('static', filename = 'main.css')}}">
    <script src="./app.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JavaScript Events</title>
</head>
<body onload="darkCheck()">

    <nav>
        <a href="{{ url_for('my_view.home')}}">Home</a>
        <a href="{{ url_for('my_view.pg1')}}">Page 1</a>
        <a href="{{ url_for('my_view.pg2')}}">Page 2</a>
        <a href="{{ url_for('my_view.pg3')}}">Page 3</a>
        <a href="{{ url_for('my_view.pg4')}}">Page 4</a>
        <a href="{{ url_for('my_view.pg5')}}">Page 5</a>
        <a href="{{ url_for('my_view.admin')}}">Admin</a>
    </nav>
{% block content %}
{% endblock %}
<script src="{{url_for('static', filename = 'app.js')}}"></script>
</body>
</html>

project_one/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="flex-container-h">
    <div>
    <h1>JavaScript Events</h1>
    <div class="flex-container-h">
        <button onclick="toggleDM()">Dark Mode</button>
    </div>
    <h2>Innovate Coding</h2>
    <p id="intro-text">This is an interactive website for demonstrating a selection of events in JavaScript.</p>

    <br>

    <div class="main-box">
    <h3 class="main-title">onclick Events</h3>
    <p class="main-text">This is an event that occurs as a result of the user 'clicking' a specific element.</p>
    <p onclick="changeText(this)" class="example-text">click this text to change it</p>
    <div class="flex-container-h2">
    <button onclick="displayDate(date)" class="example-button">Display Date</button>
    <p class="example-text" id="date"></p>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">onload Events</h3>
    <p class="main-text">This is an event that occurs as soon as the user has loaded the web page.</p>
    <p class="example-text" id="cookie"></p>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Mouse Events</h3>
    <p class="main-text">This is an event that occurs when the user moves their cursor over a specific element.</p>
    <div class="flex-container-h3">
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Extra:</h3>
        <p class="main-text">Additional features that can be used in developing a website with JavaScript.</p>
        <h4 class="main-text">Alert</h4>

        <p class="main-text">An alert is used to notify the user via a pop-up window.</p>
        <button onclick="sendAlert()" class="example-button">Display Host Name</button>
        <h4 class="main-text">Toggle</h4>
        <p class="main-text">TBC</p>
    </div>

    <br>
    <br>

    </div>
    </div>
    {% endblock %}

project_one/templates/page1.html
{% extends 'base.html' %}
{% block content %}
<p> Future Content</p>
{% endblock %}

project_one/templates/page2.html
{% extends 'base.html' %}
{% block content %}
<p> Future Content</p>
{% endblock %}

project_one/templates/page3.html
{% extends 'base.html' %}
{% block content %}
<p> Future Content</p>
{% endblock %}

project_one/templates/page4.html
{% extends 'base.html' %}
{% block content %}
<p> Future Content</p>
{% endblock %}

project_one/templates/page5.html
{% extends 'base.html' %}
{% block content %}
<p> Future Content</p>
{% endblock %}