flask_work/app.py
from flask import Flask, render_template, redirect,Blueprint  #flask imports
from views import my_view

app = Flask(__name__) 

app.register_blueprint(my_view) #sets the blueprint

@app.errorhandler(Exception)
def page_not_found(e):
    return render_template("404.html", e=e)

if __name__=="__main__":
    app.run(debug=True, port=8000) # debugging is activated and the project is set to hosted on port 8000 (debugging should only be used in testing).

# folder structure should be:
#     main_folder
#         virtual env folder - we activate it, and that's it!
#         static folder
#             you can define more folders here if you like!
#             static files like style.css
#         templates folder
#             html files like base.html, index - anything we return with render_template
#         app.py
#         views.py

flask_work/views.py
from flask import render_template, redirect, url_for, Blueprint, request
from favs import fav_bands, add_to_list # a file I have with data, functions and variables on
# from app import app

my_view = Blueprint('my_view', __name__)

@my_view.route("/")    
def home():
    return render_template('index.html')

@my_view.route("/contact")   # when the url is our_app/contact
def contact():
    return render_template('contact.html') #return contact.html

@my_view.route("/about", methods=["GET", "POST"])   # when the url is our_app/about
def about():
    if request.method == "POST": # if the browser is submitting a post request - almost all submits are POST requests
        new_band=request.form["add_band"] #makes a new variable called new band from the form post
        add_to_list(new_band) #perform the function (which we import from my favs.py file and import on line 2) with the paramter new_band which we make on line 18

    return render_template('about.html', fav_bands=fav_bands) #return about.html with this variable taken from my py file favs, which we import on line 2

@my_view.route("/home")
def home_redirect():
    return redirect(url_for("my_view.home"))

# @my_view.route("/home")   #specifies the url the user would type in for this function to occur
# def home_redirect():
#     return redirect(url_for("my_view.home"))   #return the url for the home function specified on line 8

# @my_view.route("/homepage")
# def homeb_redirect():
#     return redirect(url_for("my_view.home"))

flask_work/templates/about.html
{% extends 'base.html' %} 
<!-- putting the content of base.html onto this page -->]

<!-- This content is unique to this page, when rendering this page, the browser will display all the content from base.html - but fill in the gaps with this content on lines 25 -->
{% block content %} 
<h3>About Page</h3>
{% for i in fav_bands %}
<h5>{{ i }}</h5>
{% endfor %}

<!-- an example of some if logic -->
{% if "Radiohead" in fav_bands %}
<h4>Radiohead? What a great band</h4>
{% endif %}
<!-- using the variable passed through with return render_template on views page -->

<form action="/about" method="post">
    <input type="text" name="add_band" id="band_add" placeholder="Enter a band!">
    <button type="submit">Submit a band</button>
</form>
{% endblock %}

flask_work/templates/base.html
<!-- All the content from this page will be used as out HTML template - we will write:
extends 'base.html' at the top of every page we want the content to appear  -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename = 'style.css')}}"> 
    <!-- url_for is the flask syntax for urls, we can't just write a relative path -->
    <title>Katy's page</title>
</head>
<body>
    
    <header>
        <nav>
            <a href="{{ url_for('my_view.home')}}">Home</a> 
            <a href="{{ url_for('my_view.contact')}}">Contact</a>
            <a href="{{ url_for('my_view.about')}}">About</a>
        </nav>
        <h1>Welcome to my website</h1>
    </header>
    <!-- this is the place holder section - on all our other pages, we'll insert content into this area using these blocks -->
    {% block content %}
    {% endblock %}
</body>
</html>

flask_work/templates/contact.html
{% extends 'base.html' %}
<!-- putting the content of base.html onto this page -->]

<!-- This content is unique to this page, when rendering this page, the browser will display all the content from base.html - but fill in the gaps with this content on lines 25 -->
{% block content %}
<h3>Contact Page</h3>
<p>Please do not contact me</p>

{% endblock %}

flask_work/templates/index.html
{% extends 'base.html' %} 
<!-- putting the content of base.html onto this page -->]

<!-- This content is unique to this page, when rendering this page, the browser will display all the content from base.html - but fill in the gaps with this content on lines 25 -->
{% block content %} 
<h3>Home Page</h3>
<p>This page is my main home page. My name is Katy, I like marine biology, rugby league, and many video games especially Genshin Impact</p>

{% endblock %}